#!/bin/bash
#
# This completes the parts of the install that aren't 
# currently/easily terraformed
#

#
# Install LoadBalancer support for nginx-ingress
#
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
#kubectk apply -f ./metallb-native.yaml

# Wait for the install to complete...
echo
echo "Waiting for metallb to complete the install..."
echo

kubectl wait --namespace metallb-system \
                --for=condition=ready pod \
                --selector=app=metallb \
                --timeout=90s

kubectl apply -f ./metallb-conf.yaml

#
# Install prometheus-stack
#
#kubectl create namespace monitoring
#helm install kind-prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --set prometheus.service.nodePort=30000 --set prometheus.service.type=NodePort --set grafana.service.nodePort=31000 --set grafana.service.type=NodePort --set alertmanager.service.nodePort=32000 --set alertmanager.service.type=NodePort --set prometheus-node-exporter.service.nodePort=32001 --set prometheus-node-exporter.service.type=NodePort
helm install --wait --timeout 15m \
   --namespace monitoring --create-namespace \
   --repo https://prometheus-community.github.io/helm-charts \
   kube-prometheus-stack kube-prometheus-stack
#helm install --wait --timeout 15m \
#   --namespace monitoring --create-namespace \
#   --repo https://prometheus-community.github.io/helm-charts \
#   kube-prometheus-stack kube-prometheus-stack --values - <<EOF 
# kubeEtcd:
#   service:
#     targetPort: 2381
# kubeControllerManager:  
#   service:
#     targetPort: 10257
# kubeScheduler:
#   service:
#     targetPort: 10259
#EOF

#
# Install argo-rollouts
#
kubectl create namespace argo-rollouts
kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml

exit 0
